services:
  # Backend API Service
  - type: web
    name: chat-hive-back-end
    runtime: node
    plan: free
    env: node
    rootDir: back-end
    buildCommand: "npm install"
    startCommand: "npm start"
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: HOST
        value: 0.0.0.0
      - key: DATABASE_URL
        sync: false
      - key: ACCESS_TOKEN_SECRET
        sync: false
      - key: REFRESH_TOKEN_SECRET
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false

  # Frontend Web Service
  - type: web
    name: chat-hive-fe
    runtime: node
    plan: free
    env: node
    rootDir: front-end
    buildCommand: "npm install && npm run build"
    startCommand: "npm run start"
    autoDeploy: true
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: "https://chat-app-backend.onrender.com/api"
      - key: NEXT_PUBLIC_WS_URL
        value: "wss://chat-app-backend.onrender.com"
