version: "3.8"

services:
  backend:
    build: .
    ports:
      - "9090:9090"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: ""
      DB_NAME: chatt-app
    volumes:
      - .:/src
      - /src/node_modules # avoid overwriting container's node_modules
    command: npm start # ensure nodemon is used instead of default CMD

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: chatt-app
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql  
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    depends_on:
      db:
        condition: service_healthy

# Define named volume for MySQL data persistence
volumes:
  mysql_data: