version: "3.8"

services:
  backend:
    build: .
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: ""
      DB_NAME: chatt-app
    volumes:
      - .:/src
      - /src/node_modules  # avoid overwriting container's node_modules
    command: npm start  # ensure nodemon is used instead of default CMD

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: chatt-app
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
